#ifndef SWGISPLUGINSCONFIG_H
#define SWGISPLUGINSCONFIG_H

#ifdef SWGISPLUGINS_LIB
# define SWGISPLUGINS_EXPORT Q_DECL_EXPORT
#else
# define SWGISPLUGINS_EXPORT Q_DECL_IMPORT
#endif

#endif // SWGISPLUGINSCONFIG_H
