#ifndef STGISCONFIG_H
#define STGISCONFIG_H

#ifdef SWGISWMSPROVIDER_LIB
# define SWGISWMSPROVIDER_EXPORT Q_DECL_EXPORT
#else
# define SWGISWMSPROVIDER_EXPORT Q_DECL_IMPORT
#endif

#endif // STGISCONFIG_H
