#ifndef STGISCONFIG_H
#define STGISCONFIG_H

#ifdef SWGISOGRPROVIDER_LIB
# define SWGISOGRPROVIDER_EXPORT Q_DECL_EXPORT
#else
# define SWGISOGRPROVIDER_EXPORT Q_DECL_IMPORT
#endif

#endif // STGISCONFIG_H
